# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1679c125ee8a4f259a48d4b9889421e4878375f488fb86d253aec5e6dbc031752ce14914ba20b74da56c0d9b2f0c4b9700d3abc6ecb14d9e5f2e808c4e94e301

test:
  secret_key_base: 1133ae82eaf174a15efe5c7119310e76392010e235b9eb0091552dcb2d4787828e63fed97f1693f04d45c265e788318bb0124c31c74343e4760398fc313edfe0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
